import { Geist, Geist_Mono, Oswald } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/provider/useProvider"

const oswald = Oswald({
  subsets: ['latin', 'vietnamese'],
  weight: ['200', '400', '700'],
  variable: '--font-oswald', // Khai báo biến ở đây
  display: 'swap',
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${oswald.className} antialiased max-w-5xl mx-auto`}>
        <UserProvider>
            {children}
        </UserProvider>
      </body>
    </html>
  );
}

