import { Covered_By_Your_Grace, Geist, Geist_Mono, Inter, Oswald } from "next/font/google";
import "../globals.css";
import { UserProvider } from "@/provider/useProvider"
import Header from "@/components/layout/header"

const oswald = Oswald({
  subsets: ['latin', 'vietnamese'],
  weight: ['200', '400', '700'],
  variable: '--font-oswald',
  display: 'swap',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const inter = Inter({
  subsets: ['latin', 'vietnamese'],
  variable: "--font-inter",
  display: 'swap',
});

const covered = Covered_By_Your_Grace({
  subsets: ['latin'],
  weight: "400",
  variable: "--font-covered",
  display: 'swap',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${oswald.variable} ${inter.variable} ${covered.variable} antialiased max-w-[1440px] mx-auto`}>
        <UserProvider>
            <Header></Header>
            {children}
        </UserProvider>
      </body>
    </html>
  );
}

